defconfig: enable CONFIG_SYNC_DEBUG to resolve errors after commit: staging: sync: Remove fence names by default
* In drivers/gpu/msm/kgsl_sync.h there's an ifdef for "char name[32];"

* So we need to enable CONFIG_SYNC_DEBUG via defconfig so "char name [32];"
* will be declared to avoid compilation errors after having implemented the
* commit =>  staging: sync: Remove fence names by default

***************************
../../../../../../kernel/lge/msm8992/include/trace/../../drivers/staging/android/trace/sync.h: In function 'ftrace_get_offsets_sync_wait':
../../../../../../kernel/lge/msm8992/include/trace/../../drivers/staging/android/trace/sync.h:41:24: error: 'struct sync_fence' has no member named 'name'
    __string(name, fence->name)
                        ^
***************************